apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: front-end
  namespace: default
spec:
  selector:
    matchLabels:
      app: front-end
  rules:
  - to:
    - operation:
        methods: ["GET"]