---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-v3
spec:
  selector:
    matchLabels:
      app: front-end
      version: v3
  template:
    metadata:
      labels:
        app: front-end
        version: v3
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: front-end
        image: kdop/generic-service:0.0.5
        imagePullPolicy: Always
        env:
          - name: SCHED_CALL_URL_LST
            value: "http://front-end:8000/s"
          - name: SCHED_CALL_INTERVAL
            value: "10"
          - name: SPLIT_CALL_URL_LST
            value: "http://login:8000/,http://catalogue:8000/,http://orders:8000/s"
          - name: APP
            value: "front-end"
          - name: VERSION
            value: "v3"
        ports:
        - containerPort: 8080