apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  selector:
    matchLabels:
      app: front-end
      version: "1.0"
  template:
    metadata:
      labels:
        app: front-end
        version: "1.0"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: front-end
        image: weaveworksdemos/micro-sock
        args: ["-l", "login", "catalogue", "orders"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  selector:
    matchLabels:
      app: login
      version: "1.0"
  template:
    metadata:
      labels:
        app: login
        version: "1.0"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: login
        image: weaveworksdemos/micro-sock
        args: ["-l"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
spec:
  selector:
    matchLabels:
      app: catalogue
      version: "1.0"
  template:
    metadata:
      labels:
        app: catalogue
        version: "1.0"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: catalogue
        image: weaveworksdemos/micro-sock
        args: ["-l"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 50m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  selector:
    matchLabels:
      app: orders
      version: "1.0"
  template:
    metadata:
      labels:
        app: orders
        version: "1.0"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: orders
        image: weaveworksdemos/micro-sock
        args: ["-l"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 50m
            memory: 128Mi
        # readinessProbe:
        #   initialDelaySeconds: 15
        #   exec:
        #     command: ["-l", "orders"]
        # livenessProbe:
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        #   exec:
        #     command: ["-l", "orders"]