---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-v1
spec:
  selector:
    matchLabels:
      app: front-end
      version: v1
  template:
    metadata:
      labels:
        app: front-end
        version: v1
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: front-end
        image: kdop/generic-service:0.0.5
        imagePullPolicy: Always
        env:
          - name: SCHED_CALL_INTERVAL
            value: "300"
          - name: SPLIT_CALL_URL_LST
            value: "http://login:8000/,http://catalogue:8000/,http://orders:8000/s"
          - name: APP
            value: "front-end"
          - name: VERSION
            value: "v1"
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-v2
spec:
  selector:
    matchLabels:
      app: front-end
      version: v2
  template:
    metadata:
      labels:
        app: front-end
        version: v2
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: front-end
        image: kdop/generic-service:0.0.5
        env:
          - name: SCHED_CALL_INTERVAL
            value: "300"
          - name: SPLIT_CALL_URL_LST
            value: "http://login:8000/,http://catalogue:8000/,http://orders:8000/s"
          - name: APP
            value: "front-end"
          - name: VERSION
            value: "v2"
        ports:
        - containerPort: 8080
