
apiVersion: v1
kind: Namespace
metadata:
  name: financial
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit
  namespace: financial
spec:
  selector:
    matchLabels:
      app: credit
      version: v1
  template:
    metadata:
      labels:
        app: credit
        version: v1
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: orders
        image: kdop/generic-service:0.0.5
        imagePullPolicy: Always
        env:
          - name: APP
            value: "credit"
          - name: VERSION
            value: "v1"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: financial
  name: credit
  labels:
    app: credit
spec:
  type: ClusterIP
  selector:
    app: credit
  ports:
  - name: http
    port: 8000
    targetPort: 8000