---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  selector:
    matchLabels:
      app: orders
      version: v1
  template:
    metadata:
      labels:
        app: orders
        version: v1
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: orders
        image: kdop/generic-service:0.0.5
        imagePullPolicy: Always
        env:
          - name: SPLIT_CALL_URL_LST
            value: "http://shipping:8000/s,http://cart:8000/s,http://orders-db:8000/,http://payment:8000/,http://accounts:8000/s,http://credit.financial:8000/,http://httpbin.org/uuid"
          - name: APP
            value: "orders"
          - name: VERSION
            value: "v1"
        ports:
        - containerPort: 8080