---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: front-end
  namespace: default
spec:
  host: front-end
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
    - name: all-pods
      labels: 
        app: front-end
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: front-end
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
  - default-gateway
  http:
  - match:
    - uri:
        prefix: /front-end
    rewrite:
      uri: /
    route:
    - destination:
        host: front-end # FQDN completo ou abreviado
        subset: all-pods
  - route: # <-- rota padrão
    - destination:
        host: front-end 
        subset: all-pods
